#! /usr/bin/env bash

set -euo pipefail

# Build demos website
cd demos/
rm -rf public/
mkdir -p public/

for input in src/Examples/*.elm
do
  name="$(basename "${input}" ".elm")"
  output="public/${name}.html"
  npx elm make "${input}" --output "${output}" --optimize

  # Insert Viewport meta tag for better mobile experience
  tag='<meta name="viewport" content="width=device-width, initial-scale=0.75">'
  sed -i "s|</head>|  ${tag}\n</head>|" "${output}"
done

cp index.html public/
cp -r assets public/

cd -
