#! /usr/bin/env bash

set -euo pipefail

# To make it work on OSX (provided gnu-sed in installed)
if type gsed
then
  sed=gsed
fi


git diff-index --quiet HEAD -- \
  || (echo "There are uncommited changes. Aborting." ; exit 1)

echo "Determining scope of changes. Please wait."
elm bump

version=$(jq --raw-output ' .version ' "elm.json")
date=$(date +%Y-%m-%d)

$sed \
  --regexp-extended \
  --in-place="" \
  "s$^## \[Unreleased\]$\## [Unreleased\]\n\n\n## [${version}] - ${date}$" \
  CHANGELOG.md

npm version --no-git-tag-version "${version}"

git --no-pager diff

while true
do
  read \
    -p "Do you approve this changes? [y/n] > " \
    -n 1 \
    -r \
    approved

    case ${approved} in
      [yY])
        echo
        echo "Ok, commiting."
        break
        ;;
      [nN])
        echo
        echo "Ok, aborting."
        git checkout HEAD .
        exit 0
        ;;
      *)
        echo
        echo "Invalid input. Try again."
        ;;
    esac
done

git commit -am "Release ${version}"
git tag -a ${version} -m "Release ${version}"
git push
git push --tags

# Push to a mirror
git push github
git push github --tags
elm publish
